name: download-m3u8-mp4

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  v2ray-ngrok:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Download .m3u8 to .mp4
        run: |
          ffmpeg -i "https://m3u.haiwaikan.com/xm3u8/1e9395cb059270b2a27a010ad6c6e8e083652d686f4d672215fc109557e848f39921f11e97d0da21.m3u8" "the-nun-2.mp4"
          ffmpeg -i "https://hot.1080pzy.co/20230919/XaJrTpoG/index.m3u8" "a-haunting-in-venice.mp4"

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.0.0"
          # draft: "false"
          prerelease: "false" # default is true
          # title: "v2ray client json files"
          files: |
            *.mp4
